"""
Guardrailed query execution module for PartnerLens Copilot.

Phase 8 execution controls:

- Revalidates SQL immediately before execution.
- Opens SQLite in read-only mode.
- Enforces a query execution timeout.
- Guarantees database connection cleanup.
- Verifies that returned rows remain within the validated limit.
- Returns execution metadata for auditing and evaluation.
- Prevents raw database errors from being exposed to users.
"""

from contextlib import closing
from dataclasses import dataclass
from pathlib import Path
import sqlite3
import time

import pandas as pd

from src.sql_validator import validate_sql_detailed


DATABASE_PATH = Path("data/processed/partnerlens.db")
DEFAULT_QUERY_TIMEOUT_SECONDS = 10.0


@dataclass(frozen=True)
class QueryExecutionResult:
    """
    Structured result returned after successful SQL execution.

    Attributes:
        dataframe: Query results as a pandas DataFrame.
        status: Execution status.
        row_count: Number of rows returned.
        columns: Columns returned by the query.
        source_tables: Tables approved by the SQL validator.
        validated_row_limit: LIMIT value approved by the validator.
        elapsed_ms: Query execution time in milliseconds.
        database_name: Database filename without exposing its full path.
    """

    dataframe: pd.DataFrame
    status: str
    row_count: int
    columns: tuple[str, ...]
    source_tables: tuple[str, ...]
    validated_row_limit: int
    elapsed_ms: float
    database_name: str


class QueryExecutionError(Exception):
    """
    User-safe exception raised when SQL cannot be executed.

    The reason_code can be stored in audit logs without exposing
    sensitive database or filesystem information.
    """

    def __init__(
        self,
        reason_code: str,
        safe_message: str,
    ) -> None:
        super().__init__(safe_message)
        self.reason_code = reason_code
        self.safe_message = safe_message


def resolve_database_path(
    db_path: Path | str = DATABASE_PATH,
) -> Path:
    """
    Resolve and verify the SQLite database path.

    The full resolved path should not be shown in user-facing messages.
    """

    resolved_path = Path(db_path).expanduser().resolve()

    if not resolved_path.exists():
        raise QueryExecutionError(
            reason_code="database_not_found",
            safe_message=(
                "The PartnerLens database could not be found."
            ),
        )

    if not resolved_path.is_file():
        raise QueryExecutionError(
            reason_code="invalid_database_path",
            safe_message=(
                "The configured PartnerLens database path is invalid."
            ),
        )

    return resolved_path


def create_read_only_connection(
    db_path: Path | str = DATABASE_PATH,
) -> sqlite3.Connection:
    """
    Open the PartnerLens SQLite database in read-only mode.

    SQLite URI mode=ro prevents inserts, updates, deletes, schema
    changes, and accidental database creation.
    """

    resolved_path = resolve_database_path(db_path)

    database_uri = f"{resolved_path.as_uri()}?mode=ro"

    try:
        connection = sqlite3.connect(
            database_uri,
            uri=True,
            timeout=5.0,
        )

        # Adds an additional database-level read-only control.
        connection.execute("PRAGMA query_only = ON")

        return connection

    except sqlite3.Error as error:
        raise QueryExecutionError(
            reason_code="database_connection_failed",
            safe_message=(
                "A read-only connection to the PartnerLens database "
                "could not be established."
            ),
        ) from error


def execute_query_detailed(
    sql: str,
    db_path: Path | str = DATABASE_PATH,
    timeout_seconds: float = DEFAULT_QUERY_TIMEOUT_SECONDS,
) -> QueryExecutionResult:
    """
    Validate and execute a read-only PartnerLens SQL query.

    Args:
        sql: SQL generated by the approved PartnerLens SQL planner.
        db_path: Path to the SQLite database.
        timeout_seconds: Maximum allowed query execution duration.

    Returns:
        QueryExecutionResult containing the DataFrame and audit metadata.

    Raises:
        QueryExecutionError: When validation or execution fails.
    """

    if timeout_seconds <= 0:
        raise QueryExecutionError(
            reason_code="invalid_timeout",
            safe_message=(
                "The query timeout must be greater than zero."
            ),
        )

    # Defense in depth: validate again immediately before execution.
    validation = validate_sql_detailed(sql)

    if not validation.is_valid:
        raise QueryExecutionError(
            reason_code=f"validation_{validation.reason_code}",
            safe_message=(
                "The generated SQL was not executed because it failed "
                f"the PartnerLens safety checks. {validation.message}"
            ),
        )

    if validation.row_limit is None:
        raise QueryExecutionError(
            reason_code="missing_validated_limit",
            safe_message=(
                "The generated SQL was not executed because it did not "
                "have an approved result limit."
            ),
        )

    resolved_path = resolve_database_path(db_path)
    start_time = time.monotonic()

    try:
        with closing(
            create_read_only_connection(resolved_path)
        ) as connection:

            def stop_long_running_query() -> int:
                """
                Interrupt SQLite when the approved timeout is exceeded.

                SQLite calls this function periodically while processing
                the query. Returning 1 stops execution.
                """

                elapsed_seconds = time.monotonic() - start_time

                if elapsed_seconds > timeout_seconds:
                    return 1

                return 0

            connection.set_progress_handler(
                stop_long_running_query,
                1_000,
            )

            try:
                result_df = pd.read_sql_query(
                    sql,
                    connection,
                )
            finally:
                connection.set_progress_handler(None, 0)

    except QueryExecutionError:
        raise

    except sqlite3.OperationalError as error:
        elapsed_seconds = time.monotonic() - start_time

        if (
            "interrupted" in str(error).lower()
            or elapsed_seconds > timeout_seconds
        ):
            raise QueryExecutionError(
                reason_code="query_timeout",
                safe_message=(
                    "The query was stopped because it exceeded the "
                    "approved execution time."
                ),
            ) from error

        raise QueryExecutionError(
            reason_code="database_operational_error",
            safe_message=(
                "The query could not be completed by the PartnerLens "
                "database."
            ),
        ) from error

    except (sqlite3.Error, pd.errors.DatabaseError) as error:
        raise QueryExecutionError(
            reason_code="query_execution_failed",
            safe_message=(
                "The query could not be executed safely."
            ),
        ) from error

    elapsed_ms = round(
        (time.monotonic() - start_time) * 1_000,
        2,
    )

    row_count = len(result_df)

    # Defense in depth: verify the database did not return more rows
    # than the validator approved.
    if row_count > validation.row_limit:
        raise QueryExecutionError(
            reason_code="result_limit_exceeded",
            safe_message=(
                "The returned result exceeded the approved row limit."
            ),
        )

    return QueryExecutionResult(
        dataframe=result_df,
        status="success",
        row_count=row_count,
        columns=tuple(result_df.columns),
        source_tables=validation.referenced_tables,
        validated_row_limit=validation.row_limit,
        elapsed_ms=elapsed_ms,
        database_name=resolved_path.name,
    )


def execute_query(
    sql: str,
    db_path: Path | str = DATABASE_PATH,
) -> pd.DataFrame:
    """
    Backward-compatible query execution function.

    Existing code can continue using:

        result_df = execute_query(sql)

    Use execute_query_detailed when execution metadata is needed.
    """

    execution_result = execute_query_detailed(
        sql=sql,
        db_path=db_path,
    )

    return execution_result.dataframe


def dataframe_to_records(
    result_df: pd.DataFrame,
) -> list[dict]:
    """
    Convert a query DataFrame into records for answer generation.

    This creates the input expected by generate_answer().
    """

    if result_df.empty:
        return []

    safe_df = result_df.where(
        pd.notna(result_df),
        None,
    )

    return safe_df.to_dict(orient="records")
